from datetime import datetime, timezone
from app.models.article import Article


def dt(s: str) -> datetime:
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


SEED_ARTICLES = [
    # ── Maccabi Tel Aviv Basketball ───────────────────────────────
    Article(
        id="article_001",
        source="sport5",
        source_display_name="ספורט 5",
        url="https://www.sport5.co.il/articles.aspx?FolderID=1&docID=1",
        title="דיווח: מכבי ת״א במו״מ עם גארד יורוליג",
        language="he",
        published_at=dt("2026-06-11T08:00:00Z"),
        sport="basketball",
        league="EuroLeague",
        entities=["Maccabi Tel Aviv Basketball"],
        event_type="negotiation",
        importance="high",
        confidence=0.92,
        tags=["מכבי ת״א", "יורוליג", "מו״מ"],
    ),
    Article(
        id="article_002",
        source="sport5",
        source_display_name="ספורט 5",
        url="https://www.sport5.co.il/articles.aspx?FolderID=1&docID=2",
        title="רשמי: מכבי ת״א חתמה על קנטר מצרפת",
        language="he",
        published_at=dt("2026-06-10T14:00:00Z"),
        sport="basketball",
        league="Israeli Basketball League",
        entities=["Maccabi Tel Aviv Basketball"],
        event_type="signing",
        importance="high",
        confidence=0.97,
        tags=["מכבי ת״א", "חתימה"],
    ),
    Article(
        id="article_003",
        source="one",
        source_display_name="ONE",
        url="https://www.one.co.il/Article/3",
        title="פציעה: שחקן מכבי ת״א יהיה מחוץ לפעילות שלושה שבועות",
        language="he",
        published_at=dt("2026-06-10T10:00:00Z"),
        sport="basketball",
        league="Israeli Basketball League",
        entities=["Maccabi Tel Aviv Basketball"],
        event_type="injury",
        importance="high",
        confidence=0.95,
        tags=["מכבי ת״א", "פציעה"],
    ),
    Article(
        id="article_004",
        source="sportando",
        source_display_name="Sportando",
        url="https://sportando.basketball/article/4",
        title="מכבי ת״א בודקת גארד ששיחק ביורוליג",
        original_title="Maccabi Tel Aviv monitoring EuroLeague guard",
        translated_title="מכבי ת״א בודקת גארד ששיחק ביורוליג",
        language="en",
        published_at=dt("2026-06-09T12:00:00Z"),
        sport="basketball",
        league="EuroLeague",
        entities=["Maccabi Tel Aviv Basketball"],
        event_type="candidate",
        importance="medium",
        confidence=0.82,
        tags=["מכבי ת״א", "יורוליג", "מועמד"],
    ),
    Article(
        id="article_005",
        source="sport5",
        source_display_name="ספורט 5",
        url="https://www.sport5.co.il/articles.aspx?FolderID=1&docID=5",
        title="מכבי ת״א תשחק משחק ידידות מול קבוצת BSL לקראת העונה",
        language="he",
        published_at=dt("2026-06-08T09:00:00Z"),
        sport="basketball",
        league="Israeli Basketball League",
        entities=["Maccabi Tel Aviv Basketball"],
        event_type="friendly_match",
        importance="low",
        confidence=0.90,
        tags=["מכבי ת״א", "ידידות"],
    ),

    # ── NBA ────────────────────────────────────────────────────────
    Article(
        id="article_006",
        source="eurohoops",
        source_display_name="Eurohoops",
        url="https://www.eurohoops.net/article/6",
        title="הורנטס מנצחים את וויזארדס 112-105 בליגה הרגילה",
        original_title="Hornets beat Wizards 112-105 in regular season",
        translated_title="הורנטס מנצחים את וויזארדס 112-105 בליגה הרגילה",
        language="en",
        published_at=dt("2026-06-07T22:00:00Z"),
        sport="basketball",
        league="NBA",
        entities=["Charlotte Hornets", "Washington Wizards"],
        event_type="regular_season_result",
        importance="medium",
        confidence=0.98,
        tags=["NBA", "הורנטס", "וויזארדס"],
    ),
    Article(
        id="article_007",
        source="eurohoops",
        source_display_name="Eurohoops",
        url="https://www.eurohoops.net/article/7",
        title="רשמי: דני אבדיה נסחר לקבוצה חדשה ב-NBA",
        original_title="Official: Deni Avdija traded to new NBA team",
        translated_title="רשמי: דני אבדיה נסחר לקבוצה חדשה ב-NBA",
        language="en",
        published_at=dt("2026-06-07T18:00:00Z"),
        sport="basketball",
        league="NBA",
        entities=["Deni Avdija", "Portland Trail Blazers"],
        event_type="major_trade",
        importance="high",
        confidence=0.99,
        tags=["NBA", "דני אבדיה", "טרייד"],
    ),
    Article(
        id="article_008",
        source="sportando",
        source_display_name="Sportando",
        url="https://sportando.basketball/article/8",
        title="דני אבדיה נפצע — צפוי להיעדר 4 שבועות",
        original_title="Deni Avdija injured — expected to miss 4 weeks",
        translated_title="דני אבדיה נפצע — צפוי להיעדר 4 שבועות",
        language="en",
        published_at=dt("2026-06-06T15:00:00Z"),
        sport="basketball",
        league="NBA",
        entities=["Deni Avdija"],
        event_type="injury",
        importance="high",
        confidence=0.96,
        tags=["NBA", "דני אבדיה", "פציעה"],
    ),
    Article(
        id="article_009",
        source="eurohoops",
        source_display_name="Eurohoops",
        url="https://www.eurohoops.net/article/9",
        title="גמר NBA: סלטיקס מנצחים את הית' 4-1 ומזכים את העיר בוסטון",
        original_title="NBA Finals: Celtics beat Heat 4-1 to win championship",
        translated_title="גמר NBA: סלטיקס מנצחים את הית' 4-1 ומזכים את העיר בוסטון",
        language="en",
        published_at=dt("2026-06-05T23:00:00Z"),
        sport="basketball",
        league="NBA",
        entities=["Boston Celtics", "Miami Heat"],
        event_type="finals_result",
        importance="very_high",
        confidence=1.0,
        tags=["NBA", "גמר", "אלוף"],
    ),
    # NBA major trade — no Deni, very_high importance → tests importance boost cap
    Article(
        id="article_010",
        source="eurohoops",
        source_display_name="Eurohoops",
        url="https://www.eurohoops.net/article/10",
        title="בלוקבאסטר: לייקרס וסאנס מבצעים עסקת טרייד ענקית",
        original_title="Blockbuster: Lakers and Suns complete massive trade",
        translated_title="בלוקבאסטר: לייקרס וסאנס מבצעים עסקת טרייד ענקית",
        language="en",
        published_at=dt("2026-06-04T20:00:00Z"),
        sport="basketball",
        league="NBA",
        entities=["Los Angeles Lakers", "Phoenix Suns"],
        event_type="major_trade",
        importance="very_high",
        confidence=0.97,
        tags=["NBA", "טרייד", "לייקרס", "סאנס"],
    ),

    # ── Tennis ────────────────────────────────────────────────────
    Article(
        id="article_011",
        source="walla",
        source_display_name="וואלה ספורט",
        url="https://sport.walla.co.il/article/11",
        title="אלקאראז זוכה בגראנד סלאם — מאשר שלטון מוחלט על החצר",
        language="he",
        published_at=dt("2026-06-03T17:00:00Z"),
        sport="tennis",
        league=None,
        entities=["Carlos Alcaraz"],
        event_type="grand_slam_winner",
        importance="very_high",
        confidence=1.0,
        tags=["טניס", "גראנד סלאם", "אלקאראז"],
    ),
    Article(
        id="article_012",
        source="walla",
        source_display_name="וואלה ספורט",
        url="https://sport.walla.co.il/article/12",
        title="וימבלדון: אלקאראז מתקדם לסיבוב שלישי לאחר ניצחון קל",
        language="he",
        published_at=dt("2026-06-02T16:00:00Z"),
        sport="tennis",
        league="Wimbledon",
        entities=["Carlos Alcaraz"],
        event_type="early_round_result",
        importance="low",
        confidence=0.95,
        tags=["טניס", "וימבלדון", "אלקאראז"],
    ),

    # ── Football ──────────────────────────────────────────────────
    Article(
        id="article_013",
        source="sport5",
        source_display_name="ספורט 5",
        url="https://www.sport5.co.il/articles.aspx?FolderID=1&docID=13",
        title="תוצאה: הפועל ת״א מפסידה לבית״ר ירושלים 2-1 בליגת העל",
        language="he",
        published_at=dt("2026-06-01T21:00:00Z"),
        sport="football",
        league="Israeli Premier League",
        entities=["Hapoel Tel Aviv FC", "Beitar Jerusalem FC"],
        event_type="regular_season_result",
        importance="low",
        confidence=0.95,
        tags=["כדורגל", "ליגת העל", "הפועל ת״א"],
    ),

    # ── EuroLeague ────────────────────────────────────────────────
    Article(
        id="article_014",
        source="eurohoops",
        source_display_name="Eurohoops",
        url="https://www.eurohoops.net/article/14",
        title="ריאל מדריד מגייסים את קנרד מ-NBA בצעד הרכש הגדול של הקיץ",
        original_title="Real Madrid sign Kennard from NBA in biggest summer move",
        translated_title="ריאל מדריד מגייסים את קנרד מ-NBA בצעד הרכש הגדול של הקיץ",
        language="en",
        published_at=dt("2026-06-01T14:00:00Z"),
        sport="basketball",
        league="EuroLeague",
        entities=["Real Madrid Basketball"],
        event_type="major_transfer",
        importance="high",
        confidence=0.93,
        tags=["יורוליג", "ריאל מדריד", "גיוס"],
    ),

    # ── European domestic basketball ──────────────────────────────
    # ACB playoff — high importance → should be visible for Guy (high_importance_only mode)
    Article(
        id="article_015",
        source="eurohoops",
        source_display_name="Eurohoops",
        url="https://www.eurohoops.net/article/15",
        title="ACB: ריאל מדריד מנצחים את ברצלונה בגמר ומזכים תואר",
        original_title="ACB: Real Madrid beat Barcelona in finals to win title",
        translated_title="ACB: ריאל מדריד מנצחים את ברצלונה בגמר ומזכים תואר",
        language="en",
        published_at=dt("2026-05-31T20:00:00Z"),
        sport="basketball",
        league="Spanish ACB",
        entities=["Real Madrid Basketball", "FC Barcelona Basketball"],
        event_type="playoff_result",
        importance="high",
        confidence=0.99,
        tags=["ACB", "ריאל מדריד", "ברצלונה", "גמר"],
    ),
    # Greek league regular season — low importance → hidden for Guy
    Article(
        id="article_016",
        source="eurohoops",
        source_display_name="Eurohoops",
        url="https://www.eurohoops.net/article/16",
        title="Greek League: לוח משחקים לסיבוב הבא — ניקוס ופנתיינאיקוס",
        original_title="Greek League: Schedule for next round — Nika vs Panathinaikos",
        translated_title="Greek League: לוח משחקים לסיבוב הבא — ניקוס ופנתיינאיקוס",
        language="en",
        published_at=dt("2026-05-30T19:00:00Z"),
        sport="basketball",
        league="Greek Basket League",
        entities=["Panathinaikos BC"],
        event_type="schedule",
        importance="very_low",
        confidence=0.95,
        tags=["Greek League", "פנתיינאיקוס", "לו״ז"],
    ),
]


def seed_articles(db) -> None:
    for article in SEED_ARTICLES:
        db.articles[article.id] = article
