from app.models.calibration import CalibrationHeadline

SEED_CALIBRATION_HEADLINES = [
    CalibrationHeadline(
        id="cal_001",
        title="מכבי ת״א בשלבי מו״מ מתקדמים עם גארד יורוליגי",
        sport="basketball", league="EuroLeague",
        entities=["Maccabi Tel Aviv Basketball"],
        event_type="negotiation", importance="high",
        tags=["מכבי ת״א", "יורוליג", "מו״מ"],
    ),
    CalibrationHeadline(
        id="cal_002",
        title="מכבי ת״א חותמת רשמית עם פורוורד מליגה הספרדית",
        sport="basketball", league="Israeli Basketball League",
        entities=["Maccabi Tel Aviv Basketball"],
        event_type="signing", importance="high",
        tags=["מכבי ת״א", "חתימה"],
    ),
    CalibrationHeadline(
        id="cal_003",
        title="פציעה במכבי: שחקן מרכזי צפוי להיות מחוץ לפעילות חודש",
        sport="basketball", league="Israeli Basketball League",
        entities=["Maccabi Tel Aviv Basketball"],
        event_type="injury", importance="high",
        tags=["מכבי ת״א", "פציעה"],
    ),
    CalibrationHeadline(
        id="cal_004",
        title="מכבי ת״א בודקת מועמד פורוורד מהליגה הצרפתית",
        sport="basketball", league="EuroLeague",
        entities=["Maccabi Tel Aviv Basketball"],
        event_type="candidate", importance="medium",
        tags=["מכבי ת״א", "מועמד"],
    ),
    CalibrationHeadline(
        id="cal_005",
        title="מכבי ת״א תשחק משחק ידידות מול קבוצה גרמנית בטורניר הכנה",
        sport="basketball", league="Israeli Basketball League",
        entities=["Maccabi Tel Aviv Basketball"],
        event_type="friendly_match", importance="low",
        tags=["מכבי ת״א", "ידידות"],
    ),
    CalibrationHeadline(
        id="cal_006",
        title="ריאל מדריד חותמת על גארד אמריקאי — רכש יורוליג גדול",
        sport="basketball", league="EuroLeague",
        entities=["Real Madrid Basketball"],
        event_type="major_signing", importance="high",
        tags=["יורוליג", "ריאל מדריד"],
    ),
    CalibrationHeadline(
        id="cal_007",
        title="פנלתיינאיקוס מנצח את CSKA מוסקבה בגמר הפיינל פור",
        sport="basketball", league="EuroLeague",
        entities=["Panathinaikos BC", "CSKA Moscow"],
        event_type="finals_result", importance="very_high",
        tags=["יורוליג", "פיינל פור", "גמר"],
    ),
    CalibrationHeadline(
        id="cal_008",
        title="הורנטס מנצחים את וויזארדס 112-105 בסיבוב רגיל",
        sport="basketball", league="NBA",
        entities=["Charlotte Hornets", "Washington Wizards"],
        event_type="regular_season_result", importance="medium",
        tags=["NBA", "הורנטס", "וויזארדס"],
    ),
    CalibrationHeadline(
        id="cal_009",
        title="רשמי: דני אבדיה נסחר לקבוצה חדשה ב-NBA",
        sport="basketball", league="NBA",
        entities=["Deni Avdija", "Portland Trail Blazers"],
        event_type="major_trade", importance="high",
        tags=["NBA", "דני אבדיה", "טרייד"],
    ),
    CalibrationHeadline(
        id="cal_010",
        title="דני אבדיה נפצע — יהיה מחוץ לפעילות 4 שבועות",
        sport="basketball", league="NBA",
        entities=["Deni Avdija"],
        event_type="injury", importance="high",
        tags=["NBA", "דני אבדיה", "פציעה"],
    ),
    CalibrationHeadline(
        id="cal_011",
        title="גמר NBA: סלטיקס מנצחים ומזכים אלופות",
        sport="basketball", league="NBA",
        entities=["Boston Celtics", "Miami Heat"],
        event_type="finals_result", importance="very_high",
        tags=["NBA", "גמר", "אלוף"],
    ),
    CalibrationHeadline(
        id="cal_012",
        title="ACB: ריאל מדריד מנצחים את ברצלונה בגמר — אלופי ספרד",
        sport="basketball", league="Spanish ACB",
        entities=["Real Madrid Basketball", "FC Barcelona Basketball"],
        event_type="playoff_result", importance="high",
        tags=["ACB", "ריאל מדריד", "ברצלונה"],
    ),
    CalibrationHeadline(
        id="cal_013",
        title="אלקאראז זוכה בגראנד סלאם — מאשר שלטון על החצר",
        sport="tennis", league=None,
        entities=["Carlos Alcaraz"],
        event_type="grand_slam_winner", importance="very_high",
        tags=["טניס", "גראנד סלאם", "אלקאראז"],
    ),
    CalibrationHeadline(
        id="cal_014",
        title="וימבלדון: אלקאראז מתקדם לסיבוב שלישי לאחר ניצחון",
        sport="tennis", league="Wimbledon",
        entities=["Carlos Alcaraz"],
        event_type="early_round_result", importance="low",
        tags=["טניס", "וימבלדון"],
    ),
    CalibrationHeadline(
        id="cal_015",
        title="הפועל ת״א מפסידה לבית״ר ירושלים 2-1 בליגה הרגילה",
        sport="football", league="Israeli Premier League",
        entities=["Hapoel Tel Aviv FC", "Beitar Jerusalem FC"],
        event_type="regular_season_result", importance="low",
        tags=["כדורגל", "ליגת העל"],
    ),
    CalibrationHeadline(
        id="cal_016",
        title="מבאפה חותם רשמית עם ריאל מדריד — ההעברה הגדולה של הקיץ",
        sport="football", league="La Liga",
        entities=["Kylian Mbappe", "Real Madrid FC"],
        event_type="major_transfer", importance="very_high",
        tags=["כדורגל", "מבאפה", "ריאל מדריד"],
    ),
]


def seed_calibration_headlines(db) -> None:
    db.calibration_headlines = list(SEED_CALIBRATION_HEADLINES)
