from app.models.profile import UserProfile, TopicPreference

SEED_PROFILES = [
    UserProfile(
        user_id="guy",
        display_name="Guy",
        language="he",
        profile_type="basketball_power_user",
        topics=[
            TopicPreference(
                topic_id="maccabi_tel_aviv_basketball",
                label="מכבי ת״א כדורסל",
                sport="basketball",
                priority=100,
                mode="all",
                leagues=["Israeli Basketball League", "EuroLeague"],
                entities=["Maccabi Tel Aviv Basketball", "Oded Katash"],
                event_rules={
                    "signing": "push",
                    "major_signing": "push",
                    "negotiation": "push",
                    "injury": "push",
                    "title_win": "push",
                    "candidate": "high_feed",
                    "rumor": "high_feed",
                    "playoff_result": "high_feed",
                    "match_result": "feed",
                    "match_summary": "feed",
                    "regular_season_result": "feed",
                    "interview": "feed",
                    "analysis": "feed",
                    "opinion": "feed",
                    "friendly_match": "low_feed",
                    "pre_match": "hidden",
                    "schedule": "hidden",
                    "generic_preview": "hidden",
                },
            ),
            TopicPreference(
                topic_id="nba",
                label="NBA",
                sport="basketball",
                priority=90,
                mode="all",
                leagues=["NBA"],
                entities=["Deni Avdija"],
                entity_event_rules={
                    "Deni Avdija": {
                        "major_trade": "push",
                        "injury": "push",
                    }
                },
                event_rules={
                    "star_trade": "push",
                    "major_trade": "high_feed",
                    "title_win": "push",
                    "finals_result": "high_feed",
                    "playoff_result": "high_feed",
                    "injury": "feed",
                    "signing": "feed",
                    "major_signing": "high_feed",
                    "record": "high_feed",
                    "regular_season_result": "feed",
                    "match_result": "feed",
                    "match_summary": "feed",
                    "interview": "feed",
                    "analysis": "feed",
                    "generic_preview": "low_feed",
                    "schedule": "hidden",
                },
            ),
            TopicPreference(
                topic_id="euroleague",
                label="יורוליג",
                sport="basketball",
                priority=95,
                mode="all",
                leagues=["EuroLeague"],
                entities=["Maccabi Tel Aviv Basketball"],
                event_rules={
                    "signing": "high_feed",
                    "major_signing": "high_feed",
                    "negotiation": "high_feed",
                    "major_transfer": "high_feed",
                    "candidate": "feed",
                    "injury": "feed",
                    "match_result": "feed",
                    "match_summary": "feed",
                    "regular_season_result": "feed",
                    "playoff_result": "high_feed",
                    "final_four": "high_feed",
                    "title_win": "push",
                    "interview": "feed",
                    "analysis": "feed",
                    "opinion": "feed",
                    "generic_preview": "low_feed",
                    "schedule": "hidden",
                },
            ),
            TopicPreference(
                topic_id="israeli_basketball",
                label="כדורסל ישראלי",
                sport="basketball",
                priority=85,
                mode="all",
                leagues=["Israeli Basketball League"],
                entities=[],
                event_rules={
                    "signing": "feed",
                    "major_signing": "high_feed",
                    "negotiation": "feed",
                    "candidate": "feed",
                    "injury": "feed",
                    "match_result": "feed",
                    "regular_season_result": "feed",
                    "match_summary": "feed",
                    "playoff_result": "high_feed",
                    "title_win": "high_feed",
                    "interview": "feed",
                    "analysis": "feed",
                    "opinion": "feed",
                    "friendly_match": "low_feed",
                    "generic_preview": "low_feed",
                    "schedule": "hidden",
                },
            ),
            TopicPreference(
                topic_id="major_european_domestic_basketball",
                label="ליגות כדורסל בכירות באירופה",
                sport="basketball",
                priority=65,
                mode="high_importance_only",
                leagues=["Spanish ACB", "Turkish BSL", "Greek Basket League", "Italian LBA", "French LNB"],
                entities=[],
                event_rules={
                    "major_match_result": "feed",
                    "playoff_result": "feed",
                    "title_win": "high_feed",
                    "major_signing": "feed",
                    "euroleague_related_transfer": "high_feed",
                    "regular_season_result": "hidden",
                    "generic_regular_season_result": "hidden",
                    "match_result": "hidden",
                    "generic_preview": "hidden",
                    "schedule": "hidden",
                },
            ),
            TopicPreference(
                topic_id="football",
                label="כדורגל",
                sport="football",
                priority=20,
                mode="major_only",
                leagues=[],
                entities=[],
                event_rules={
                    "major_transfer": "feed",
                    "title_win": "feed",
                    "major_match_result": "low_feed",
                    "match_summary": "low_feed",
                    "regular_season_result": "hidden",
                    "generic_regular_season_result": "hidden",
                    "match_result": "hidden",
                    "generic_preview": "hidden",
                    "schedule": "hidden",
                    "interview": "hidden",
                    "opinion": "hidden",
                    "analysis": "hidden",
                },
            ),
            TopicPreference(
                topic_id="tennis",
                label="טניס",
                sport="tennis",
                priority=25,
                mode="titles_only",
                leagues=[],
                entities=[],
                event_rules={
                    "grand_slam_winner": "high_feed",
                    "grand_slam_final": "feed",
                    "early_round_result": "hidden",
                    "generic_news": "hidden",
                    "match_result": "hidden",
                    "regular_season_result": "hidden",
                    "analysis": "hidden",
                    "schedule": "hidden",
                },
            ),
        ],
        muted_topics=[],
        muted_sources=[],
        followed_entities=["Maccabi Tel Aviv Basketball", "Deni Avdija", "Oded Katash"],
    ),
    UserProfile(
        user_id="casual_deni_fan",
        display_name="אוהד דני קז׳ואל",
        language="he",
        profile_type="casual_entity_follower",
        topics=[
            TopicPreference(
                topic_id="nba",
                label="NBA",
                sport="basketball",
                priority=45,
                mode="followed_entities_only",
                leagues=["NBA"],
                entities=["Deni Avdija"],
                entity_event_rules={
                    "Deni Avdija": {
                        "major_trade": "push",
                        "injury": "push",
                        "regular_season_result": "high_feed",
                        "record": "high_feed",
                    }
                },
                event_rules={
                    "regular_season_result": "feed",
                    "match_result": "feed",
                    "match_summary": "feed",
                    "injury": "feed",
                    "major_trade": "feed",
                    "star_trade": "feed",
                    "finals_result": "feed",
                    "playoff_result": "feed",
                    "record": "feed",
                    "interview": "feed",
                    "analysis": "feed",
                    "generic_preview": "hidden",
                    "schedule": "hidden",
                    "signing": "hidden",
                    "followed_entity_news": "high_feed",
                },
            ),
        ],
        muted_topics=[],
        muted_sources=[],
        followed_entities=["Deni Avdija"],
    ),
]


def seed_profiles(db) -> None:
    for profile in SEED_PROFILES:
        db.profiles[profile.user_id] = profile
